[0m21:11:14.225441 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11a6eb3d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11a83a5d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11ab71050>]}


============================== 21:11:14.228282 | c8880726-68f0-4dd2-bd56-2210194d9593 ==============================
[0m21:11:14.228282 [info ] [MainThread]: Running with dbt=1.6.5
[0m21:11:14.228618 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/juan.domingos/.dbt', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt init .', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m21:11:20.786714 [error] [MainThread]: Encountered an error:

[0m21:11:20.790435 [error] [MainThread]: Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/dbt/cli/requires.py", line 87, in wrapper
    result, success = func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/dbt/cli/requires.py", line 72, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/dbt/cli/main.py", line 469, in init
    results = task.run()
              ^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/dbt/task/init.py", line 283, in run
    project_name = self.get_valid_project_name()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/dbt/task/init.py", line 246, in get_valid_project_name
    name = click.prompt("Enter a name for your project (letters, digits, underscore)")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/termui.py", line 166, in prompt
    value = prompt_func(prompt)
            ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/termui.py", line 149, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m21:11:20.791111 [debug] [MainThread]: Command `dbt init` failed at 21:11:20.790990 after 6.59 seconds
[0m21:11:20.791427 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11ab70b90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11ae35fd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11a82f2d0>]}
[0m21:11:20.791765 [debug] [MainThread]: Flushing usage events
[0m21:11:38.995306 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x119a2dc10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x119a1dad0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11a13b3d0>]}


============================== 21:11:38.999139 | 6143b6d2-cfaa-445e-9281-d7e6906b9a60 ==============================
[0m21:11:38.999139 [info ] [MainThread]: Running with dbt=1.6.5
[0m21:11:38.999561 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/juan.domingos/.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'invocation_command': 'dbt init aula_04_santander_coders_dbt', 'send_anonymous_usage_stats': 'True'}
[0m21:11:39.000355 [debug] [MainThread]: Starter project path: /opt/homebrew/lib/python3.11/site-packages/dbt/include/starter_project
[0m21:11:39.004672 [info ] [MainThread]: 
Your new dbt project "aula_04_santander_coders_dbt" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m21:11:39.004916 [info ] [MainThread]: Setting up your profile.
[0m21:12:02.654485 [debug] [MainThread]: Command `dbt init` succeeded at 21:12:02.654342 after 23.68 seconds
[0m21:12:02.654922 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11a134dd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x119de5850>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1027a14d0>]}
[0m21:12:02.655189 [debug] [MainThread]: Flushing usage events
[0m19:23:16.692103 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107aefa10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10832f650>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1080746d0>]}


============================== 19:23:16.695602 | 57e56197-359a-4d9c-aae0-13228d7ff53e ==============================
[0m19:23:16.695602 [info ] [MainThread]: Running with dbt=1.6.5
[0m19:23:16.695944 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'profiles_dir': '/Users/juan.domingos/.dbt', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt seed', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m19:23:16.696271 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/juan.domingos/Development/Personal/dbt-projects/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m19:23:16.696658 [debug] [MainThread]: Command `dbt seed` failed at 19:23:16.696591 after 0.02 seconds
[0m19:23:16.696861 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107d59890>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107d39490>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x100d1c7d0>]}
[0m19:23:16.697050 [debug] [MainThread]: Flushing usage events
